openapi: 3.0.0
info:
  title: CTFBox
  version: '1.0'
  contact:
    name: CTFBox
    url: 'https://github.com/CTFBox/CTFBox'
  description: CTFBox API
servers:
  - url: 'http://localhost:1323/api'
    description: local

