version: '2'

tasks:
  default:
    cmds:
      - task: run

  run:
    deps: [build]
    cmds:
      - /app/ctf_box
    sources:
      - '**/*.go'

  build:
    dir: .
    cmds:
      - go build -o /app/ctf_box
